const movies = [
  {
    title: 'The Green Mile',
    subtitle: 'Drama',
    storyline: 'Paul Edgecomb (Tom Hanks) walked the mile with a variety of cons. He had never encountered someone like John Coffey (Michael Clarke Duncan), a massive black man convicted of brutally killing a pair of young sisters. Coffey had the size and strength to kill anyone, but not the demeanor. Beyond his simple, naive nature and a deathly fear of the dark, Coffey seemed to possess a prodigious, supernatural gift. Paul began to question whether Coffey was truly guilty of murdering the two girls.',
    rating: 4.9,
    imagePath: 'images/a-espera-de-um-milagre.jpg',
    bookmarked: true,
    genre: 'drama',
  },
  {
    title: 'Interstellar',
    subtitle: 'Sci-fi/Adventure',
    storyline: 'In Earth\'s future, a global crop blight and second Dust Bowl are slowly rendering the planet uninhabitable. Professor Brand (Michael Caine), a brilliant NASA physicist, is working on plans to save mankind by transporting Earth\'s population to a new home via a wormhole. But first, Brand must send former NASA pilot Cooper (Matthew McConaughey) and a team of researchers through the wormhole and across the galaxy to find out which of three planets could be mankind\'s new home.',
    rating: 4.9,
    imagePath: 'images/interestellar.jpg',
    bookmarked: true,
    genre: 'sci-fi/adventure',
  },
  {
    title: 'The Pursuit of Happyness',
    subtitle: 'Drama',
    storyline: 'Life is a struggle for single father Chris Gardner (Will Smith). Evicted from their apartment, he and his young son (Jaden Christopher Syre Smith) find themselves alone with no place to go. Even though Chris eventually lands a job as an intern at a prestigious brokerage firm, the position pays no money. The pair must live in shelters and endure many hardships, but Chris refuses to give in to despair as he struggles to create a better life for himself and his son.',
    rating: 4.9,
    imagePath: 'images/a-procura-da-felicidade.jpg',
    bookmarked: true,
    genre: 'drama',
  },
  {
    title: 'Hacksaw Ridge',
    subtitle: 'War/Drama',
    storyline: 'The true story of Pfc. Desmond T. Doss (Andrew Garfield), who won the Congressional Medal of Honor despite refusing to bear arms during WWII on religious grounds. Doss was drafted and ostracized by fellow soldiers for his pacifist stance but went on to earn respect and adoration for his bravery, selflessness and compassion after he risked his life -- without firing a shot -- to save 75 men in the Battle of Okinawa.',
    rating: 4.9,
    imagePath: 'images/ate-o-ultimo-homem.jpg',
    bookmarked: true,
    genre: 'war/drama',
  },
  {
    title: 'The Imitation Game',
    subtitle: 'War/Drama',
    storyline: 'In 1939, newly created British intelligence agency MI6 recruits Cambridge mathematics alumnus Alan Turing (Benedict Cumberbatch) to crack Nazi codes, including Enigma -- which cryptanalysts had thought unbreakable. Turing\'s team, including Joan Clarke (Keira Knightley), analyze Enigma messages while he builds a machine to decipher them. Turing and team finally succeed and become heroes, but in 1952, the quiet genius encounters disgrace when authorities reveal he is gay and send him to prison.',
    rating: 4.8,
    imagePath: 'images/o-jogo-da-imitação.jpg',
    bookmarked: true,
    genre: 'war/drama',
  },
  {
    title: 'Sully',
    subtitle: 'Drama',
    storyline: 'On Jan. 15, 2009, Capt. Chesley "Sully" Sullenberger (Tom Hanks) tries to make an emergency landing in New York\'s Hudson River after US Airways Flight 1549 strikes a flock of geese. Miraculously, all of the 155 passengers and crew survive the harrowing ordeal, and Sullenberger becomes a national hero in the eyes of the public and the media. Despite the accolades, the famed pilot now faces an investigation that threatens to destroy his career and reputation.',
    rating: 4.7,
    imagePath: 'images/sully.jpg',
    bookmarked: true,
    genre: 'drama',
  },
  {
    title: 'The Boy in the Striped Pajamas',
    subtitle: 'War/Drama',
    storyline: 'During World War II, 8-year-old Bruno (Asa Butterfield) and his family leave Berlin to take up residence near the concentration camp where his father (David Thewlis) has just become commandant. Unhappy and lonely, he wanders out behind his house one day and finds Shmuel (Jack Scanlon), a Jewish boy of his age. Though the barbed-wire fence of the camp separates them, the boys begin a forbidden friendship, oblivious to the real nature of their surroundings.',
    rating: 4.6,
    imagePath: 'images/o-menino-do-pijama-listrado.jpg',
    bookmarked: true,
    genre: 'war/drama',
  },
  {
    title: 'Fury',
    subtitle: 'War/Action',
    storyline: 'In April 1945, the Allies are making their final push in the European theater. A battle-hardened Army sergeant named Don "Wardaddy" Collier (Brad Pitt), leading a Sherman tank and a five-man crew, undertakes a deadly mission behind enemy lines. Hopelessly outnumbered, outgunned and saddled with an inexperienced soldier (Logan Lerman) in their midst, Wardaddy and his men face overwhelming odds as they move to strike at the heart of Nazi Germany.',
    rating: 4.6,
    imagePath: 'images/coracoes-de-ferro.jpg',
    bookmarked: true,
    genre: 'war/action',
    
  },
  {
    title: 'The King',
    subtitle: 'Historical drama',
    storyline: 'Young Henry V encounters deceit, war and treachery after becoming King of England in the 15th century, in the aftermath of his brother\'s death.',
    rating: 4.6,
    imagePath: 'images/o-rei.jpg',
    bookmarked: true,
    genre: 'historical drama',
  },
  {
    title: 'Joker',
    subtitle: 'Drama/Crime',
    storyline: 'Forever alone in a crowd, failed comedian Arthur Fleck seeks connection as he walks the streets of Gotham City. Arthur wears two masks -- the one he paints for his day job as a clown, and the guise he projects in a futile attempt to feel like he\'s part of the world around him. Isolated, bullied and disregarded by society, Fleck begins a slow descent into madness as he transforms into the criminal mastermind known as the Joker.',
    rating: 4.5,
    imagePath: 'images/coringa.jpg',
    bookmarked: true,
    genre: 'drama/crime',
    
  },
];

export default movies;
